### PR TITLE
Implement edit/save tasks for News

### PR DESCRIPTION
**Pull request by mbabker**
This implements edit/save tasks similar to how we've done it for the tracker app.  The content editor is the MarkItUp editor, allowing users to input their content Markdown style.  The database has been altered to store both the raw and markdown-parsed text which is parsed via GitHub's API (using the non-GFM option).

Still need to sort out the add task and probably should implement an authentication system (just using the tracker's GitHub mechanism should suffice, but I'd drop the usergroup code for this demo).

### CODE REVIEW

**Comment by davidhurley** [comment]
I definitely don't want Github authentication or any GitHub calls in this one.

**Comment by davidhurley** [comment]
This is not a full application but just a starter sample point that should be the ultimate in flexibility.

**Comment by davidhurley** [comment]
Maybe fork this to add those examples. That way people can get an idea of what's possible but can start with a very basic barebones if they wish.

**Comment by mbabker** [comment]
Works for me.  My thought at this point is that if there's some sort of edit capability in the app, it shouldn't be wide open by default, but you're right in that it's probably going a bit further than a very basic sample should go.  That's probably an intermediate level sample.

**Pull request closed without merging**
